### ISSUE TITLE
Profile Save

### ISSUE THREAD

**Issue by Flothecop** [rex706/SAM#1]
I have a little security issue the account nickname and keyword is saved in clear text, thats potential danger the most Hacktools search in brower&apps for password or nickname... p in Files for account`s to steal them
or use Keylogger, encode them in the *.txt please

**Comment by rex706** [comment]
I'll add encryption for the account nickname for sure. What do you mean "keyword", though? If you're referencing the "PRIVATE_KEY" in the source, this is not the actual key that is pushed in the releases. If you mean the profile html or description, I could do those as well.

**Comment by Flothecop** [comment]
password/keyword it's the key for an account

**Comment by rex706** [comment]
You may be using an older version some how. Check to make sure you are using version 1.0.2.0 as that is currently the latest and the password definitely gets encrypted before saving to a file.

Could you possibly elaborate a bit more on what you mean by import/export?

**Comment by Flothecop** [comment]
Backup function
That I have not to change it if I use another System
