### ISSUE TITLE
SAM takes long time to load

### ISSUE THREAD

**Issue by Nou4r** [rex706/SAM#100]
https://streamable.com/seticl

Idk what might be causing this but its really annoying to wait a few seconds everytime i launch SAM.

**Comment by 2Eggsss** [comment]
I think it's the amount of accounts you have along with the fact that I think it checks for bans every time you open up the client

**Comment by rex706** [comment]
Like KillaBoi said it could be the number of accounts you have configured. The more you have the longer it _could_ take for the file to be decrypted. I doubt it's the ban checks, which do automatically update if you have that setting enabled, but it runs in an async method with as many steamId's it can fit into a single webapi request. 

You could try disable checking for udpates on startup?
