### ISSUE TITLE
Feature Request: Option to auto-populate profile url

### ISSUE THREAD

**Issue by infowolfe** [rex706/SAM#104]
It would be a big value-add if you were able to login to accounts automatically from SAM to auto-populate the profile url.

**Comment by rex706** [comment]
I will consider coming up with a routine to automatically login cycle through accounts which do not have the profile url or steamId populated for that account. I am also looking into supporting this information to be imported from the bulk delimited importer. I should also just add a field to enter the steamId directly if it is already known right into the input box.

**Comment by infowolfe** [comment]
For me, personally, with the number of accounts I have/have access to, having this automated within SAM makes much more sense than doing it as an import-time thing.

Logic-wise, I would recommend something like "if no steam profile set && reload ban status then login and set steam profile uri"
