### ISSUE TITLE
Button continuous touch

### ISSUE THREAD

**Issue by xiao-e-yun** [rex706/SAM#107]
Is it possible to set the button to only one click(non-sandbox mode)
otherwise, due to multiple wake-ups, normal input is not possible

**Comment by rex706** [comment]
@xiao-e-yun could you please explain a little further? what do you mean "normal input is not possible"?

**Comment by xiao-e-yun** [comment]
Maybe I enabled `remember password`（Deactivate `-login` )
When you keep clicking to log in repeatedly
it let the old timer quit SAM
And will repeat restart multiple times STEAM 
Repeat output account & passwords
也许我启用了“记住密码”（停用“ -login”）
当您持续单击以重复登录时
它让旧的计时器退出SAM
并将重新启动STEAM
重复输出帐户和密码

**Comment by rex706** [comment]
I think I understand. You want to cancel the current login thread and start a new one if multiple buttons are clicked in sequence. This makes sense.

**Comment by xiao-e-yun** [comment]
When sandbox mode is disabled,disable this login buttons until the process is complete,I often double-click, which makes the program meaningless to log in again
