### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by SmokyTheGun** [rex706/SAM#109]
the program doesnt start, it opens for a second or two and then closes without massage

**Comment by matt1tk** [comment]
same issue
:c

**Comment by matt1tk** [comment]
https://github.com/rex706/SAM/releases/tag/v1.4.1.1 works for me though @SmokyTheGun

**Comment by rex706** [comment]
Interesting. I wonder what could have changed between 1.4.1.1 and the next version. I'll take a look at the changes, but you may just need to install [.NET Framework 4.8](https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer).

**Comment by rex706** [comment]
@SmokyTheGun @matt1tk is this still an issue with the latest version and with .NET 4.8?

**Comment by matt1tk** [comment]
I'm a linux user now :sunglasses: 

However, I'm 99% certain I had .net48 installed at the time as I frequently develop with it.

**Comment by catgirlkara** [comment]
Fixed in #135
