### ISSUE TITLE
Always log in invisible/offline?

### ISSUE THREAD

**Issue by Nou4r** [rex706/SAM#110]
I want when logging in via SAM to always be shown offline or invisible. Is it possible to do that?
https://i.imgur.com/PVkt685.png

**Comment by rex706** [comment]
I've been looking into this, as I think it's actually a pretty valuable feature to have, but it's giving me a harder time than expected to figure out. This is usually controlled by the Steam Friends List window settings and then setting this: 
![image](https://user-images.githubusercontent.com/15636269/102284074-927b3f80-3f01-11eb-8558-75135702ab95.png)
to **OFF**.

It looks like it *may* be saved somewhere in the userdata folder vdf files as some similar looking settings appear there but it's difficult to tell ahead of time which folder belongs to which user and how to make them if the folders don't exist ahead of time.

There may or may not be a reliable way to do this, but I'll keep looking.

**Comment by pablo1020** [comment]
+1 for starting in offline mode

**Comment by rex706** [comment]
The config files that drive this setting are located in the Steam userdata directories: 

`...\Steam\userdata\{some id}\config\localconfig.vdf`

However, the id for the folder name is not the same id that I am used to seeing for accounts. 

I was able to test this works after finding the right one for the account I wanted and setting `"SignIntoFriends"` to `"0"`. 

I will look into matching account info to the folder structure to drive this setting. I may need to figure out how to generate them as well for accounts that are signed in for the first time.

**Comment by rex706** [comment]
Turns out the folder names are SteamID3 values and they can be found by converting them from the normal SteamID64 that is in use today. 

Websites like https://steamid.io and https://steamid.venner.io are tools to look up various info about steam accounts like of what your alternate IDs are. 

This library should help make things simpler: https://github.com/NachoReplay/SteamID-NET

**Comment by rex706** [comment]
the `localconfig.vdf` also contains a property `FriendStoreLocalPrefs_{steamid3}`, which has the value `{\"ePersonaState\":7,\"strNonFriendsAllowedToMsg\":\"\"}` where the **ePersonaState** corresponds to your online status where 1 is _Online_ and 7 is _Invisible_. These values can be changed to take affect on the next login.
