### ISSUE TITLE
"The Input is not a valid Base-64 String...."

### ISSUE THREAD

**Issue by csmit195** [rex706/SAM#111]
Hi, I'm an account reseller, I find accounts for the AU community, in last month I've handled over 500usd in cheap account transactions, and finding my specific accounts in my buying history, would be like finding a needle in a haystack.

So, long story short. My windows 10 has a bug, one that I've found impossible to fix or google about over the last 2 years, and It's causing issues. Essentially, I run VM's on my PC, always at 12/16gb ram, and after enough time, eventually I'm unable to open up new processes, including, task manager, shutdown.exe, or even an empty file explorer. The ONLY way to fix it, is to force a shutdown by holding the power button, I did so while SAM was running, and it corrupted my info.dat file. which had 10 of my most valued accounts stored in it!

Also as to google being unhelpful, googling "PC wont shutdown or start programs" seems to only show result about why windows 10 wont shut down, my issue isnt that it wont shutdown, its that the literal process (shutdown.exe) cant start as no process will. I've reinstalled windows multiples times, I've come to the conclusion over the years, that its a hardware / driver issue and it is what it is... It happens daily btw...

Who can I talk to about having the .dat file repaired? Or solutions? I need these accounts, at the very least, the usernames...

Cheers,
Chris...

**Comment by csmit195** [comment]
![image](https://user-images.githubusercontent.com/5733443/91615944-0c75d000-e9c8-11ea-97a5-ad9558023405.png)

**Comment by csmit195** [comment]
![image](https://user-images.githubusercontent.com/5733443/91616167-8a39db80-e9c8-11ea-94dd-6fd5659398b7.png)

**Comment by KillaBoi** [comment]
Hello fellow skeet user!

Did you encrypt your info.dat file by any chance? The info.dat file is usually just a XML file with all your data on it, if it looks like that then there's a chance it might've corrupted to a point where it's unrecoverable... did you make any backups or anything?

**Comment by rex706** [comment]
Unfortunately I think @KillaBoi is right. It looks like your info.dat file is corrupt, and if that is the case then there really isn't anything I can do to recover your account data. What I can do, though, is look into making a backup feature that would save up to a user-defined amount of backup info.dat files into a separate folder of the user's choosing so there will ideally always be at least one valid backed up data file every time the main info.dat is written to in the event this happens again.
