### ISSUE TITLE
when i open the source in visual studio i get a error

### ISSUE THREAD

**Issue by widow-9098** [rex706/SAM#115]
error`Severity	Code	Description	Project	File	Line	Suppression State
Error	XDG0008	Button is not supported in a Windows Presentation Foundation (WPF) project.	SAM	SettingsWindow.xaml	26	
`

**Comment by rex706** [comment]
Build > Clean Solution. Then Build > Build Solution. Then restart VS and Start SAM. Not sure why I had to do this for it to work.
