### ISSUE TITLE
-developer flag is invalid

### ISSUE THREAD

**Issue by pointydev** [rex706/SAM#118]
Hey there,

Currently, the settings have an option for the `-developer` parameter to be used. This parameter doesn't exist, as can be seen [here](https://developer.valvesoftware.com/wiki/Command_Line_Options#Steam_(Windows)). The correct flag is `-dev`.

Thanks,
Elliott

**Comment by rex706** [comment]
You can temporarily get around this by enabling the custom parameters box and adding it manually there for now until it is fixed.
