### ISSUE TITLE
Steam Accoun Manager not started

### ISSUE THREAD

**Issue by mrwhaler** [rex706/SAM#119]
https://github.com/sandboxie-plus/Sandboxie/issues/312

**Comment by rex706** [comment]
I don't personally use Sandboxie, or any similar VM with SAM for that matter. I currently have no plans to install it. 

From the issue you linked it seems like this is an issue with running on startup? Is that the correct assumption? 

The current run on startup implementation just copies a shortcut to SAM to the startup folder.

**Comment by mrwhaler** [comment]
Greetings! Normal startup runs without errors. Running through the avast sandbox also goes without errors. The error is only in this program. I made the settings in the ini file (SandboxMode = True)

**Comment by rex706** [comment]
Unfortunately I do not experience any error with SAM not starting when SandBoxMode=True. This feature prevents Steam from being shut down between logins, so it is possible multiple instances of Steam can run at the same time under certain conditions. If this is not what you intend to use it for then you can keep SandBoxMode=False. The original ticket for this item was #75

**Comment by mrwhaler** [comment]
I decided to check again, since I postponed attempts to figure out the error. Launched it with a new version of the sandbox installation and the program started without errors. I think the issue can be considered resolved.
