### ISSUE TITLE
Crashes with saved accounts

### ISSUE THREAD

**Issue by notFunnys** [rex706/SAM#121]
SAM is saving my account but if i close the window i cant open it again (crash)
[NET 4.8](https://i.imgur.com/KhUh8BP.png)

Translated: .NET Framework 4.8 or a newer update is already installed on this computer.

**Comment by rex706** [comment]
Depending on where you have SAM installed, you may need to run it as Administrator. Reading/writing your data and settings files does not work in places like the Programs Folders without elevated privileges.

**Comment by rex706** [comment]
Is this still a problem? I am unable to reproduce this issue and therefor cannot make a fix for it.

**Comment by catgirlkara** [comment]
duplicates #109

**Comment by catgirlkara** [comment]
Fixed in #135
