### ISSUE TITLE
crashes when I run

### ISSUE THREAD

**Issue by faw187** [rex706/SAM#124]
Downloaded. Launched, pressed and then crash. I restart it anyway, the crash tried on behalf of the administrator does not work. Latest version

**Comment by rex706** [comment]
Where is SAM installed? I have no issues downloading a fresh version and using it normally.

**Comment by KevAquila** [comment]
Having same issue, left it in the download folder, moved it to C:\ and they both crash right after passing the password prompt.

**Comment by Majentas** [comment]
it's a bug with, SAMSettings.ini, just delete it and it works again, all your accounts will be restored

**Comment by catgirlkara** [comment]
duplicates #121

**Comment by catgirlkara** [comment]
Fixed in #135
