### ISSUE TITLE
crashes when i run

### ISSUE THREAD

**Issue by walladinmamafet** [rex706/SAM#125]
so after updating it it crashes when i run it. i tried reverting but now it seems like it doesnt work anymore. i got about 500 accounts, and if this doesnt get fixed theyre gone forever

**Comment by Majentas** [comment]
it's a bug with, SAMSettings.ini, just delete it and it works again, all your accounts will be restored

**Comment by gr1ndy** [comment]
> it's a bug with, SAMSettings.ini, just delete it and it works again, all your accounts will be restored

my accs didnt restore..

**Comment by rex706** [comment]
I don't ever experience a crash with SAM. Without additional details about what is going on I can't do much to help. You could try Majentas suggestion and delete *only* the settings file and try running it again. Account data is stored in info.dat.

**Comment by dylancl** [comment]
> it's a bug with, SAMSettings.ini, just delete it and it works again, all your accounts will be restored

This worked for me.

**Comment by catgirlkara** [comment]
#135 This should be fixed in my pull request

**Comment by catgirlkara** [comment]
duplicates #124

**Comment by catgirlkara** [comment]
Fixed in #135
