### ISSUE TITLE
Failed to load steamui.dll

### ISSUE THREAD

**Issue by cartoonjs1** [rex706/SAM#127]
Steam opens normally when i manually open it but when i try to login with SAM it says Failed to load steamui.dll
![image](https://user-images.githubusercontent.com/70315324/115984124-1af3a600-a5ae-11eb-9bb2-dc7b8dd3b178.png)

**Comment by rex706** [comment]
Please make sure the Steam path is correct in the settings for SAM. All SAM does it run steam with certain command line parameters.

**Comment by karmakarmakarmakarmakarma** [comment]
Getting this one too

**Comment by Gtt1229** [comment]
The same issue was occurring for me.

1. Check Steam install path
2. Ensure SAM is run as admin
