### ISSUE TITLE
SAM  does not fill  2fa column when Steam start in Avast Sandbox

### ISSUE THREAD

**Issue by dudits777** [rex706/SAM#136]
Hi, I Need to **start many Steam**  accounts at same time, and im using **Avast sandbox** for it, but   **SAM doesnt wont to fill  2fa code column**, when Steam works from under the Avast sandbox. It prints the login and password normally, and the column for 2fa just remains empty. 

Outside the sandbox, everything works fine. **NetFramework 4.8 is installed**, everything is added to the Avast exceptions. I run SAM  as an administrator and in **SendWait** mode. Is it possible to somehow solve this problem? I'm sure there is some solution, please help.
_P.s.  I have Russian Windows 10, but my  Steam  client in English, and without Avast Sandbox SAM work fine with 2fa column._

**Comment by rex706** [comment]
@dudits777  It works for me using the `SendMessage` input method.
