### ISSUE TITLE
All accounts are randomly gone/everything resets after opening the program again

### ISSUE THREAD

**Issue by ulea** [rex706/SAM#137]
No clue what causes it, it's happened 2 times now, and each time it happens, it's after I have not had the program open for a bit. It's really weird, it's like it'll be fine, and open with all my accs and everything, then just randomly, next time I go to open it, everything is gone. The settings page also resets at the same time when everything else disappears. 

Would this be an issue with it not saving properly when the application is closed? I doubt it would be, as I stated earlier, I was able to open the program a few times without any issue before it reset. 

Any clue what's up with it? It's getting kind of annoying having to reinput all my acc info and 2fa/shared secret for all my accs so often, it's more effort than it's worth right now.

**Comment by Nou4r** [comment]
Its a issue with the password protection, turn it off and you wont face such issues.

**Comment by ulea** [comment]
as much as I'd like the fix to be easy and "just turn off ___" I am 99% sure that I didn't have password protection on in the first place. I will try this again though, thanks for the idea.

**Comment by kadeler** [comment]
Usually i get it fixed by pressing Edit → Refresh, but sometimes it just crashes when im tryna log into some account, so i have to manually import from it's own .dat file, and delete the copies i got
Doesn't bother that much since i only have 2 accs, but would be nice if it got fixed
