### ISSUE TITLE
Importing user:password accounts not working

### ISSUE THREAD

**Issue by itay0246** [rex706/SAM#138]
Hello, i tried to import some accounts with few formats and everytime i do that seems like the info.dat file is being buggy and not allowing the program to work well and because of that i lost access to 3 old accounts i had in my old info.dat file
i tried to following formats:
user:pass
user:pass:
user:pass:<blank>
seems like everything is not working my accounts does not have shared secret from the far i know because im not using SDA

**Comment by rex706** [comment]
@itay0246 I do not experience any issue importing accounts from the delimiter window using the format: `user:pass` since you are not using shared secrets. My info.dat file looks normal and is working as expected.
