### ISSUE TITLE
1.2.3.0 crash when entering

### ISSUE THREAD

**Issue by wazerstar** [rex706/SAM#14]
Going to edit > settings makes the app freeze and then crash.

**Comment by rex706** [comment]
Interesting. I have not had this issue when testing. Worst case scenario you should be able to delete your SAMSettings.ini and reconfigure what you had. This should not affect the accounts you currently have set up. 

Someone else had reported this issue before, so I will have to take a closer look into why this could be happening.

**Comment by wazerstar** [comment]
I just did it 3 times with clean installation of sam

Windows 10 x64 16gb 8700k 1080ti gfx, latest updates as of today.

**Comment by rex706** [comment]
Looking into it now. Thanks for the update.

**Comment by rex706** [comment]
After downloading a clean install from the Releases tab and extracting a fresh SAM_1.2.3.0.zip into it's own folder with nothing but SAM.exe and Updater.exe, SAM loads up fine and I do not crash when clicking on Settings through the menu. 

Is there anything else you can provide me?

**Comment by wazerstar** [comment]
My windows is totally fresh, I just checked an ryzen machine too, did the same. You said you had another guy doing it too, i think there needs to be some checks and sleep/loose something up and be 100% sure the app is started steam/sam.

**Comment by rex706** [comment]
I had another friend with an 8700k download a fresh copy on his machine and had no crash issues opening the settings. 

I really want to help solve your issue, so feel free to add me on Discord so we can more quickly figure out what is wrong: rex706#6521

**Comment by GhostZAR** [comment]
I have the same issue, 1.2.2.0 was working fine until I was prompt with a new update. I updated it and when it opened, it froze for a few seconds and then closed. I tried deleting SAMSettings.ini but it was still happening. I re downloaded 1.2.2.0 and used the same info.dat and SAMSettings.ini files and it worked fine, so it has to do with this new update.

**Comment by rex706** [comment]
Well that's not good.

I will take another closer look and run some additional tests.

**Comment by rex706** [comment]
Someone from another thread isolated the problem and I have since fixed the issue and am putting together another update. Thanks for the help and sorry for the inconvenience guys.

**Comment by rex706** [comment]
I have just pushed a new update: 1.2.3.1.

Please let me know if this is still an issue.

**Comment by GhostZAR** [comment]
Seems to be working fine, thanks for the fix :)

**Comment by rex706** [comment]
Glad it's now working!

Thanks again for bringing the issue to my attention.
