### ISSUE TITLE
Please update steam switched to a new version of the interface

### ISSUE THREAD

**Issue by FelSCoM** [rex706/SAM#149]
autocomplete no longer works 🙁

**Comment by sepehrsohrabi** [comment]
Steam's new sign in interface killed auto login.
Please Fix.

**Comment by d0gkiller87** [comment]
**Solution** : Add `-noreactlogin` into `Edit` → `Settings` → `Parameters` → (box on the bottom for custom arguments)
![SAM](https://user-images.githubusercontent.com/32069685/194534158-6b08d2e2-2ca8-4e6c-b929-a2e72acc9602.png)

So they removed `-login` and a few other command line arguments for some reason, join [the discussions](https://steamcommunity.com/discussions/forum/1/3392923906943661620/) here if you are interested.  For now, you can still switch to the old client by using `-noreactlogin` flag. However, once they dropped support for the old client, we'll need a reconstructed SAM to simulate typing username/password (just like how it enters the 2FA code).

BTW, there's an active fork of SAM (https://github.com/Venipa/SAM) and they might provide similar features in the future. So go subscribe to their release as well if you are interested!

**Comment by FelSCoM** [comment]
thanks, still working

**Comment by 17sergiom2000** [comment]
thanks for the fix
