### ISSUE TITLE
Steam's new sign in interface killed auto login

### ISSUE THREAD

**Issue by sepehrsohrabi** [rex706/SAM#150]
Please Fix.

**Comment by KillaBoi** [comment]
i'm on it, will need @rex706 to accept my pull request though

**Comment by d0gkiller87** [comment]
Check out the temporary solution: https://github.com/rex706/SAM/issues/149#issuecomment-1271433637

**Comment by KillaBoi** [comment]
I committed a pull request #151 with that fix hardcoded into the launcher. If Alec is still active (I added him on discord so we will see) he can potentially push it out as an update, if need be I will take over updates and management of the project if he isn't motivated to work on it anymore since there hasn't been updates in a long time...

**Comment by d0gkiller87** [comment]
> I committed a pull request #151 with that fix hardcoded into the launcher. If Alec is still active (I added him on discord so we will see) he can potentially push it out as an update, if need be I will take over updates and management of the project if he isn't motivated to work on it anymore since there hasn't been updates in a long time...

Sounds great. I think we should also start to work on the `Type2FA()` method so it handles the username/password window. Also I guess I'll use @Venipa's fork as the base since it's more recently maintained. What do you think?

**Comment by Venipa** [comment]
![image](https://user-images.githubusercontent.com/17952364/194546508-87aa6509-1198-4481-8c2e-acdb29432ab4.png)
add `-noreactlogin` to custom params input in settings

**Comment by KillaBoi** [comment]
> > I committed a pull request #151 with that fix hardcoded into the launcher. If Alec is still active (I added him on discord so we will see) he can potentially push it out as an update, if need be I will take over updates and management of the project if he isn't motivated to work on it anymore since there hasn't been updates in a long time...
> 
> Sounds great. I think we should also start to work on the `Type2FA()` method so it handles the username/password window. Also I guess I'll use @Venipa's fork as the base since it's more recently maintained. What do you think?
> 
> Edit: The `TypeCredentials()` method is already there to simulate username/password input when `-login` option is toggled off. Unfortunately, for some reasons the new Steam ui doesn't receive key inputs (e.g. `PostMessage()`) even after `SetForegroundWindow()` was called until the user manually left-clicked the login window to focus it.

I spoke to Alec, he said he was going to work on merging @Venipa's fork into the codebase as well :)
