### ISSUE TITLE
need help /mafile

### ISSUE THREAD

**Issue by desmanSTAR** [rex706/SAM#155]
hi, explain how to add a mafile to the program SAM
i use my {"shared_secret":"2L8IJuHlb++++ULK0pAtYDlFiXyM="   2L8IJuHlb++++ULK0pAtYDlFiXyM=  --- I add this code in the settings, but it doesn't work
thanks for the help

**Comment by rex706** [comment]
Copy/paste your code '2L8IJuHlb++++ULK0pAtYDlFiXyM=' into the '2FA Shared Secret' field for the account it belongs to. It does not go in settings.

**Comment by desmanSTAR** [comment]
that's exactly what I did

> @desmanSTAR copy/paste your code `2L8IJuHlb++++ULK0pAtYDlFiXyM=` into the `2FA Shared Secret` field for the account it belongs to. It does not go in settings.
 
that's exactly what I did. (not in settings, but editing) did not explain correctly

**Comment by rex706** [comment]
Can you better explain exactly what doesn't work? As long as you put that code on the correct account it should behave correctly. Verify you are not including any extra spaces.

**Comment by desmanSTAR** [comment]
your truth I checked everything on my laptop, everything works fine there. maybe I need to reinstall Windows or SDA.
very curious why. 
I truly appreciate all your time spent on this.
