### ISSUE TITLE
Crahses if using old .dat file

### ISSUE THREAD

**Issue by Prostar13810** [rex706/SAM#16]
If you load the new update with old .dat file or import it, the program freezes. The reason for this is this line is not in the old .dat files, and the program doesn't know what to do without it.

<SharedSecret>numbers and stuff</SharedSecret>

If the <SharedSecret> is not in .dat file, the program will just freeze. Maybe when you update or import it, you create the new line?

Hope this helps you some how.

**Comment by rex706** [comment]
Thank you very much for bringing this to my attention. I was having a hard time isolating the issue. I'll push a new update that handles this scenario soon.

**Comment by rex706** [comment]
I have just pushed a new update that should address this issue.

Let me know if the problem still persists.

Thanks again for actually isolating the problem.

**Comment by Prostar13810** [comment]
Yep fixed, sorry wrote issues and didn't realise Github comments don't like Greater than and Less than symbols, the line was "SharedSecret". Sorry about that. 

The Update fixed the issue, thank you.

Would it be possible to import accounts from a text file
user:pass
user:pass
for saved accounts in text file.

Thank you and keep up the good work.

**Comment by rex706** [comment]
Great! Glad it's working.

I will definitely look into some kind of mass import option, but the problem then becomes how to allow input for some fields and not others without having to have users build their own XML or JSON files. For example, when trying to utilize the new 2FA supported field. 

Thanks again for identifying the problem!
