### ISSUE TITLE
Writes out the wrong 2fa code

### ISSUE THREAD

**Issue by strobecsmain** [rex706/SAM#164]
I made an SDA and found this fucking file with the .myfile extension, but after transferring the text from this damn file, SAM started writing incorrect code that was different from the code that SDA gave me. What should I do if I get the message "2FA Failed. Please verify your shared secret code is correct"

**Comment by rex706** [comment]
@strobecsmain you only need the text within quotations following "shared_secret", not the entire text within the file.
