### ISSUE TITLE
remote server returned an error:(403) Prohibited

### ISSUE THREAD

**Issue by DanishUlrik** [rex706/SAM#169]
What does this even mean? It pops up randomly when my SAM is running, also, Im on windows 11

**Comment by rex706** [comment]
@DanishUlrik SAM will automatically refresh some profile information, like bans, from the Steam servers on a set interval defined in the "Steam" tab of the SAM settings window. This should only run if a valid API key is present. "403 prohibited" is an http response code that is being returned from the Steam servers and probably means your API key is invalid. You can click the (?) button to the right of the API Key field to open the Steam page where you can get a new one, or clear the field in SAM to disable the functionality.
