### ISSUE TITLE
Suggestion allow us to export accounts by selecting those we want to be exported.

### ISSUE THREAD

**Issue by wazerstar** [rex706/SAM#17]
As topic says, right now there's no way to export desired account by choice :)

I know there's other prioritizes, just wanted to add it before I forgot about it again.

**Comment by rex706** [comment]
@wazerstar Is right clicking an account to export via the context menu good enough? Or were you looking for something more along the lines of selecting the accounts you want to batch export?

**Comment by wazerstar** [comment]
What about letting us mark accounts then be able to export selected?

**Comment by rex706** [comment]
In the new version, go the Select option under Export in the File menu and click on each account you would like to export :)
