### ISSUE TITLE
steam update broke sam

### ISSUE THREAD

**Issue by FelSCoM** [rex706/SAM#171]
autocomplete not working with latest steam version please update sam

**Comment by FelSCoM** [comment]
does not work correctly only with steam authenticator

**Comment by MichaelDavidGK** [comment]
For now you can just use steams own account manager
It only requires you to put 2FA once (if you tick the box to remember you), afterwards will login automatically when you press on account image

**Comment by FelSCoM** [comment]
This is understandable, but I would like it to be like before =)

**Comment by rex706** [comment]
The latest update seems to have broken the command-line login functionality for 2FA enabled accounts. they also seem to have moved all of the relevant steam windows under a different steam process. I'm working on a solution
