### ISSUE TITLE
cant login with 1.5.2.0 update

### ISSUE THREAD

**Issue by salem2012** [rex706/SAM#174]
i had to go back to 1.5.1.0
login credentials shows empty in steam while using SAM 1.5.2.0

**Comment by ccsimplyspolit** [comment]
also have that error on login
---------------------------
Login Error
---------------------------
Error logging in: Steam returned "GeneralFailure".
---------------------------
OK   
---------------------------

**Comment by rex706** [comment]
do you use any custom parameters?

**Comment by salem2012** [comment]
> 

-noreactlogin -login -noverifyfiles

**Comment by rex706** [comment]
@salem2012 try without -noreactlogin
