### ISSUE TITLE
Invalid base-64-string

### ISSUE THREAD

**Issue by DanishUlrik** [rex706/SAM#176]
I recently updated the program to 1.5.2 and it started saying

The input is not a valid base-64 string because it contains a non-base-64 character, more than two padding characters, or an invalid character among the padding characters
Its not 100% accurate as it has been run through google translate but it should get the message across.
Is there any way to fix this?

**Comment by DanishUlrik** [comment]
I also lost all the accounts I had on it, after I updated it

**Comment by rex706** [comment]
@DanishUlrik do you build SAM yourself?

**Comment by DanishUlrik** [comment]
Not at all, I just downloaded it from here

**Comment by rex706** [comment]
Newer versions of SAM creates a backup account data file in the event the main one is corrupted. This can happen if you have lots of accounts and SAM closes for whatever reason while writing to it. A backup is made whenever the file is written to, denoted with the .bak file extension. 

There is no programmatic reason the latest update would have corrupted your data file. 

Can you check if the backup file is intact?

**Comment by DanishUlrik** [comment]
If it is the info.dat.bak you're referring to, then it would appear to be intact

**Comment by rex706** [comment]
> If it is the info.dat.bak you're referring to, then it would appear to be intact

Make another copy of that file somewhere just in case and then remove the .bak extension. Move or delete the original .dat file and let me know if that works.

**Comment by DanishUlrik** [comment]
It does start up now! I doesnt show any accounts tho

**Comment by rex706** [comment]
Can you see any account info in any of the dat files if opened in a text editor?

**Comment by DanishUlrik** [comment]
I can see account info when I open the dat files, in the windows notepad

**Comment by DanishUlrik** [comment]
The one who recommended me SAM is a programmer, so it is possible that he sent me a version he has built, but I have no clue as it is well over a year ago.

**Comment by DanishUlrik** [comment]
As I do have all the accounts' passwords written down, would it be possible to delete SAM I have, and download a new one from this here site, and it not screwing up too much from now on?

**Comment by DanishUlrik** [comment]
This is gonna be a super newbie question, but to build it and such, should I just hit the big fat blue download button?

**Comment by rex706** [comment]
Download the code from the green button on the top right of the main page for SAM. Open the .sln file in Visual Studio. The free community edition is fine if you don't already have it. Build the solution under the build file menu. This will compile the SAM executable in the bin folder of the project directory. Copy/paste your settings and data file next to the exe you built and then run it.
