### ISSUE TITLE
Accounts not logging in

### ISSUE THREAD

**Issue by cebep133** [rex706/SAM#180]
Hello. Recently, the program has ceased to automatically log into accounts.
Logins and passwords did not change Everything checked.
When you try to log in, the standard Steam window opens - empty. You have to enter your own username and password.
What's happened?

**Comment by rex706** [comment]
@cebep133 what parameters do you use? I suspect you are using -noreactlogin, which should be avoided.

**Comment by cebep133** [comment]
> @cebep133 what parameters do you use? I suspect you are using `-noreactlogin`, which should be avoided.

I do not understand what you are. I simply downloaded and used the application. Everything worked. And then suddenly it stopped.
No settings have changed. I just used the app for a discount.
Can it be removed and downloaded again?
Please tell me!

**Comment by rex706** [comment]
Can you please provide a screenshot or video of what part you get stuck on?

**Comment by cebep133** [comment]
> Can you please provide a screenshot or video of what part you get stuck on?

Yes. Of course

First shows login with  login [Screen1](https://sun9-9.userapi.com/impg/HkSCeB99k7Z9M9D_o7L_nPmBIKYQ91P-fVf4CQ/J8L1fgzf0q0.jpg?size=690x428&quality=95&sign=a1bfa182b18fa97aacf0c38eb64bd288&c_uniq_tag=KJkmybje4C8eZ53yp1ko1aCF18UUltkKSAmrCnGq-HU&type=album)
Then just a login and password input window. [Screen2](https://sun9-20.userapi.com/impg/OVXiX6vLzjlfnv3o46g91Ewf_URJvWivbjCa8A/lc9R9vwMhL4.jpg?size=692x427&quality=95&sign=97230bd8e5dfe9704bc4dd132bc6c53e&c_uniq_tag=cEl6hCXzMxXgRGxmtryU62LH84pWiVuXmhv1OvOiGEU&type=album)
That's all.

**Comment by rex706** [comment]
Looks like the `-vgui` paramater is no longer working? @wollframium can you confirm?

**Comment by wollframium** [comment]
> 

Yes, that's why the temporary solution of rollback is steam, but it's not like it puts the February version of steam, I was personally saved by the fact that I didn't update steam.

**Comment by Vahliya** [comment]
Latest hotfix resolved the issue found in the previous hotfix, nicely done, and thank you for all the work you put into this project!

**Comment by cebep133** [comment]
Thanks to the great author!
Everything works! ♥
