### ISSUE TITLE
1.5.3.0 works - others not

### ISSUE THREAD

**Issue by sndcode** [rex706/SAM#181]
just to let you know , version [1.5.3.0 Update] is working for me with the latest steam , but newer versions are just getting stuck at "SAM WOKRING" and do nothing. 

Also if you leave SAM open for longer than 2-3 hours it uses 100 % CPU

**Comment by rex706** [comment]
@sndcode What kind of environment do you run SAM in? what parameters do you use? what system language are you using? I don't experience any issues and I use SAM on a regular basis.

**Comment by sndcode** [comment]
Steam opens yes, its german language. no parameters. 
i click on the account, steam opens, thats it. no input being made, SAM title text says SAM WORKING

**Comment by rex706** [comment]
@sndcode does Steam get stuck at the account selection screen? Or the credentials input screen?
