### ISSUE TITLE
Sandbox Mode is error

### ISSUE THREAD

**Issue by wubang0930** [rex706/SAM#188]
![1718183762169](https://github.com/rex706/SAM/assets/40825663/7bf28b83-7585-4487-b853-18309f4aa0ae)
<img width="456" alt="1718183795827" src="https://github.com/rex706/SAM/assets/40825663/a653a684-14c2-4649-acd6-27f42083c836">

When I selected sandbox mode and set the Steam client to start in avast sandbox mode, when logging in through sam, there was an error message as shown in the above figure

When I click cancel, the Steam client login box will open, but the account and password will not be automatically entered

**Comment by rex706** [comment]
@wubang0930 what happens if you run SAM in Avast Sandbox mode?
