### ISSUE TITLE
Problems: Autologin (fail, where it wont accept password?)

### ISSUE THREAD

**Issue by MikkelDK** [rex706/SAM#22]
Hello,

Seems, I have problems with using "SAM" about, it will not "autologin" (not even if password <-> saved as "hashed".

What can I do?

I can make it, so I can "log in", without I need to enter the password to Steam Account every time.

If I try login (via SAM) it will show this error with:
![](https://i.gyazo.com/0421b54b694e9ecafcf3dea407e336f1.png)

**But the login works fine, SAM program will not just accept the hashed password.**

**Comment by MikkelDK** [comment]
@rex706 Maybe you have some idea?

**Comment by rex706** [comment]
@MikkelDK if both your username and password are entered _correctly_ through the SAM ui, it should have no problems logging you in normally. 

However, I know that there is a bug with the auto login feature in the current release not working for the very first account, but I have fixed that and should work fine in the next release coming out soon. 

I just got back from some time away and will get the new release out as soon as I can :)

**Comment by MikkelDK** [comment]
@rex706 

Correct, both /username and password are entered, under (+) for add them, on the "SAM" > for it **should** login on, if I "click", which it does. (But it won't accept the password as an example) - Seems it only happens on "First Account, but if I adding 2 other, it works fine"

Great to hear, the new release will upcoming soon! ;)

**Comment by rex706** [comment]
@MikkelDK Let me know if this is still an issue in the latest version

**Comment by MikkelDK** [comment]
@rex706 After I did installed the /unpacked\ the new update.

It's still made, the same problem (on First Account) as noted on 
//As a note: You **need** to delete the old **info.dat** before it works! ;-)
> If I try login (via SAM) it will show this error with:
> ![](https://camo.githubusercontent.com/1bd624cc29545b479f644dc078835c90da2d5972/68747470733a2f2f692e6779617a6f2e636f6d2f30343231623534623639346539656361666366336465613430376533333666312e706e67)

//Update 07:41 CEST: It works now after I did create (new) info.dat ;)
Thanks anyway!
