### ISSUE TITLE
It doesn't work with Steam Guard

### ISSUE THREAD

**Issue by Asmund11** [rex706/SAM#25]
I'm trying to login to account with connected Steam Guard but it doesn't login, it asks Steam Guard code. Ofc i put my "shared_secret" in settings, if you gonna tell me about it.
P.S. I tried with two different "shared_secret" codes bcs i changed my phone number in Steam, and now "shared_secret" code different in my phone app and in SDA. Difference is just 1 thing - "\". I tried to login with and without it. And i tried to login with and without "=" in the end of "shared_secret" code too.

**Comment by rex706** [comment]
@Asmund11 does any code generate and appear in the Steam Guard window at all? And you should include everything within the quotations marks but not the quotations marks themselves, which probably includes '=' at the end.

**Comment by Asmund11** [comment]
> @Asmund11 does any code generate and appear in the Steam Guard window at all? And you should include everything within the quotations marks but not the quotations marks themselves, which probably includes '=' at the end.

Nothing doesn't generate in the Steam Guard window. Just to be sure, "shared_secret" code can looks like this "\/glkgLKhlkLKgkGLkgLKGlk=" and i must put just \/glkgLKhlkLKgkGLkgLKGlk=
Right?

**Comment by Asmund11** [comment]
> @Asmund11 does any code generate and appear in the Steam Guard window at all? And you should include everything within the quotations marks but not the quotations marks themselves, which probably includes '=' at the end.

Btw SAM is stuck when i'm logging into Steam account with Steam Guard

**Comment by Asmund11** [comment]
Any help?

**Comment by rex706** [comment]
@Asmund11 If you are doing it all correctly, which is sounds like you are, then it may be an issue with the [timing](https://support.steampowered.com/kb_article.php?ref=8625-wrah-9030#notworking). I will reintroduce the Steam TimeAligner() function when generating an auth code that _should_ handle this when I get back from work later to see if that helps.

**Comment by wazerstar** [comment]
> 
> 
> > @Asmund11 does any code generate and appear in the Steam Guard window at all? And you should include everything within the quotations marks but not the quotations marks themselves, which probably includes '=' at the end.
> 
> Btw SAM is stuck when i'm trying to log into Steam account with Steam Guard

I can confirm that sam freezes when trying to login to steam, saying in windows not responding.

**Comment by rex706** [comment]
@wazerstar It freezes always? I never have any freezing issues unless the 2FA fails, which it does not for me.

**Comment by Asmund11** [comment]
> @wazerstar It freezes always? I never have any freezing issues unless the 2FA fails, which it does not for me.

2FA fails always for me, so it freezes always for me

**Comment by Asmund11** [comment]
> @wazerstar It freezes always? I never have any freezing issues unless the 2FA fails, which it does not for me.
> 
> Edit:
> SAM may freeze temporarily while waiting for the 2FA window to appear so even if Windows says it is not responding, just let it wait for Steam to prompt for the code. Let me know if you are confident it stays frozen even after the 2FA window appears.

https://streamable.com/pfj93

**Comment by Asmund11** [comment]
How to update? I see you updated the program
![Аннотация 2019-03-23 010337](https://user-images.githubusercontent.com/29029324/54857361-9e73a680-4d07-11e9-935e-ac8dcd89e43b.jpg)

**Comment by rex706** [comment]
@Asmund11 Thanks for the video clip. I'm trying to narrow down the problem. Also, the Updater is not meant to run independently and is opened by SAM when it detects there is a new update available automatically when it opens.

**Comment by Asmund11** [comment]
> @Asmund11 Thanks for the video clip. I'm trying to narrow down the problem. Also, the Updater is not meant to run independently and is opened by SAM when it detects there is a new update available automatically when it opens.
> 
> Edit:
> If you run the new Updater.exe with this URL as a launch parameter: `https://raw.githubusercontent.com/rex706/SAM/master/latest.txt`
> it will redownload the latest version of SAM
> 
> Edit 2:
> I will include another menu item under the Help menu to check for updates manually in the next update as well.

It still doesn't work for me =(
https://streamable.com/1lqxg

**Comment by rex706** [comment]
@Asmund11 I have made code changes and commits, but I have not released a new official downloadable update/release yet. 

Since I'm not entirely sure what the issue is regarding your 2FA problem, please try this pre-release version: [SAM_12.4.1-pre1.zip](https://github.com/rex706/SAM/files/2998891/SAM_12.4.1-pre1.zip) and let me know if it generates your 2FA codes.

**Comment by Asmund11** [comment]
> @Asmund11 I have made code changes and commits, but I have not released a new official downloadable update/release yet, which would appear under [releases](https://github.com/rex706/SAM/releases).
> 
> Since I'm not entirely sure what the issue is regarding your 2FA problem, please try this pre-release version: [SAM_12.4.1-pre1.zip](https://github.com/rex706/SAM/files/2998891/SAM_12.4.1-pre1.zip) and let me know if it generates your 2FA codes.

Doesn't generate. Omg. Does it generate for you?

**Comment by wazerstar** [comment]
I have tested this 12.4.1-pre1 it works better without freeze? at least what I tested and yes 2fa works still.

**Comment by Asmund11** [comment]
> I have tested this 12.4.1-pre1 it works better without freeze? at least what I tested and yes 2fa works still.

Yeah, freeze no longer exist. But generating codes... =( I can't understand what's problem

**Comment by rex706** [comment]
@Asmund11 Maybe since your system language is not English, it is having hard time finding the Steam Guard window using the FindWindow() function. Since it looks like the words "Steam Guard" are still in English no matter what, I may be able to use that instead of the entire window title. I will make another test build for you to try soon. 
![window_title](https://user-images.githubusercontent.com/15636269/54869269-605c9e00-4d6c-11e9-9c70-8b8dbde500e5.png)

**Comment by Asmund11** [comment]
> @Asmund11 Maybe since your system language is not English, it is having hard time finding the Steam Guard window using the FindWindow() function. Since it looks like the words "Steam Guard" are still in English no matter what, I may be able to use that instead of the entire window title. I will make another test build for you to try soon.
> ![window_title](https://user-images.githubusercontent.com/15636269/54869269-605c9e00-4d6c-11e9-9c70-8b8dbde500e5.png)

Ohhhh, finally, its really working with English steam language!

**Comment by wazerstar** [comment]
> 
> 
> @Asmund11 Maybe since your system language is not English, it is having hard time finding the Steam Guard window using the FindWindow() function. Since it looks like the words "Steam Guard" are still in English no matter what, I may be able to use that instead of the entire window title. I will make another test build for you to try soon.
> ![window_title](https://user-images.githubusercontent.com/15636269/54869269-605c9e00-4d6c-11e9-9c70-8b8dbde500e5.png)

Then you should look for "Steam Guard -" and not "Steam Guard", since it seems that all language uses "Steam Guard - " & "language text"

So "Steam Guard - " <- "SteamSPACEGuardSpace-Space"

This would prevent issues if people having browser/folders/other files opening named Steam Guard.

**Comment by wazerstar** [comment]
btw I think you should include and wait if window is not active, either try a second time to make steam guard window active or wait until its active, maybe like 20-30 seconds, and then give error sound or something, right now if window fail, it just stops right away.

**Comment by Asmund11** [comment]
Update download link pls, i see you fixed trouble with Steam other languages

**Comment by rex706** [comment]
@Asmund11 I will when it's ready.
