### ISSUE TITLE
File Extract from *.rar (auto Update once an week)

### ISSUE THREAD

**Issue by Flothecop** [rex706/SAM#3]
In Subfolder 

Desktop
-SAM.exe
-(folder)  [ name "SamExCode" ]
_________________________________
Auto Update function

**Comment by rex706** [comment]
If you downloaded the latest release, it should have come with 3 files, one of which should be "Updater.exe". This will check for updates on application start up if you kept it in the same directory as SAM.exe and there is a valid internet connection. If an update is found, it will acquire the updated file(s) and start the new updated program automatically.

**Comment by Flothecop** [comment]
/*SAMSettings.ini
info.dat
Updater&dll*\
In one folder and Sam.exe (not every one have a clean desktop)

**Comment by rex706** [comment]
SAMSettings.ini and info.dat are generated the first time you use the program. Just throw all of these into a folder somewhere and create a shortcut to SAM.exe. I usually extract the rar to its own directory right off the bat to avoid things getting cluttered easily.

**Comment by Flothecop** [comment]
I use Makro's for every tool in Windows
