### ISSUE TITLE
[BUG] Opening SAM > it's closing pretty fast.

### ISSUE THREAD

**Issue by MikkelDK** [rex706/SAM#30]
https://i.gyazo.com/77cb28c9ebc55812b58be58477c35a48.mp4

I did upload a gif! ;)

**Comment by MikkelDK** [comment]
@rex706 maybe you know about the problem?

**Comment by rex706** [comment]
@MikkelDK looks to me like either your SAMSettings.ini or info.dat may be corrupt. Maybe try deleting one or both?

**Comment by MikkelDK** [comment]
> @MikkelDK looks to me like either your SAMSettings.ini or info.dat may be corrupt. Maybe try deleting one or both?

awawwh really?
:-( 

/Update 18:32 - I did deleted SAMSettings.ini and it works again <3

**Comment by rex706** [comment]
@MikkelDK glad you didn't have to delete your info.dat! I'm curious to what could have been invalid to cause that issue.

**Comment by MikkelDK** [comment]
@rex706 it's just weird, sometimes, I need to "enter" the password manually :/

**Comment by rex706** [comment]
@MikkelDK that should only happen if the password you entered into SAM is incorrect. SAM just opens Steam using your username and password as [launch parameters](https://support.steampowered.com/kb_article.php?ref=5623-QOSV-5250).

**Comment by MikkelDK** [comment]
> @MikkelDK that should only happen if the password you entered into SAM is incorrect. 
Weird, the password is correct anyway! :-D 

Maybe, you should make a setting, so it's possible to "re-enter" the password, so it's saved on SAM's info.dat file maybe?

**Comment by rex706** [comment]
@MikkelDK SAM does save your password in an encrypted form. You can open info.dat with notepad to see for yourself.

**Comment by MikkelDK** [comment]
Seems, it can't find out with this type: YB;UFFr"-[r6/m)A < As an example. @rex706

**Comment by rex706** [comment]
@MikkelDK  the '-' character is most likely being interpreted as another launch parameter since that is generally the syntax used for those things. I don't think I can do anything about that with the current way SAM logs users in. I've tried to automatically type info into the login window, but the problem then becomes not being able to know if there is text in the first box (username) or not, which would then make the input cursor start at the password box.

**Comment by MikkelDK** [comment]
@rex706 thanks for know! I think, i will remove the '-' ;) seems, SAM will not let it login with '-' ;)

Thanks anyway, and have a great afternoon! ;) <3
