### ISSUE TITLE
Decrypted password

### ISSUE THREAD

**Issue by LynxKik** [rex706/SAM#34]
Add a way to export decrypted password.

**Comment by rex706** [comment]
Oops you're right. I forgot about exporting with data encryption enabled.

**Comment by LynxKik** [comment]
No no, i mean't add an option to export plain text password so we can log into via our browser, I use password gen so I forget my passwords.

**Comment by rex706** [comment]
@LynxKik oh you mean the Steam account passwords themselves. A copy password item in right click context menu should be fine for this, but I feel weird about exposing that. Then again if the application password protection is enabled it really shouldn't be an issue. 

I'll see what I can do.

**Comment by LynxKik** [comment]
I don't think encryption makes that much of a difference, Since it's being locally hosted on your local device, It would make sense if it were hosted on a server but than again the encryption would be easy to break since it isn't an one way hash, Can you explain me the idea behind local encryption?

**Comment by rex706** [comment]
If you use the new password protection feature that some users requested, you can supply your own password to use as a key to hash the entire info.dat file, which could then only be decrypted using the chosen password. While it's not a perfect system, it should be good enough for people with security concerns. You can enable this in the settings window.

Regardless, I went ahead and implemented the 'Copy Password' item in the right-click context menu for account buttons and it will be available in the next release :)
