### ISSUE TITLE
Support for username:password accounts

### ISSUE THREAD

**Issue by marius137** [rex706/SAM#36]
When you buy accounts they often get sent in a username:password format, can you add support so there is a textbox where you just paste that string and everything gets extracted from that

**Comment by a6d6061ed1** [comment]
I think it could be useful to add a function that'd make http requests to steam and validate credentials and on the way it could retrieve steamid and such so you no longer would have to login first in order for steamid to be found.

**Comment by veaxl** [comment]
please make a program that simulates a banana being put into a stock photo to verify users.

**Comment by Roger42069** [comment]
Listen bub! You stock photo image fuck, I know your an Indian terrorist

**Comment by Roger42069** [comment]
Ill give you 4 hours to delete the comment before im exposing ur ip!

**Comment by Roger42069** [comment]
Im super serial!!!!

**Comment by veaxl** [comment]
it is an autoclicking indian buff account, destroy it

**Comment by Roger42069** [comment]
Its probably a thot bot infiltrating github smh

**Comment by marius137** [comment]
@Roger42069 still waiting for you to expose the IP

**Comment by rex706** [comment]
@marius137 do you get these in bulk? Like separated by commas for example? If not, it's hard for me to justify doing this if it's only saving you a single copy/paste action.

**Comment by marius137** [comment]
I get them in bulk, one line per account

User:pw
User:pw

And so on...

**Comment by rex706** [comment]
@marius137 Understood, I will consider adding this.

**Comment by pontifezo** [comment]
Also please add accounts import option with a shared secret

user1:password1:sharedsecret1
user2:password2:sharedsecret2

and so on...

**Comment by marius137** [comment]
I just tried out the new bulk import and it always crashes when I klick on import. The problem is that the manager expects user:PW:secret, but I only get my accounts without the secret.

A dirty workaround is to just add :1 to the account:pw line

**Comment by rex706** [comment]
@marius137 Interesting. Thought I made a check for that. Will update it when I get home today!
