### ISSUE TITLE
ability to add a countdown to an account

### ISSUE THREAD

**Issue by marius137** [rex706/SAM#37]
Can you add a feature where you can set a timeout for an account for when you get a temp ban

**Comment by Darthagnon** [comment]
might also be useful on normal, unbanned accounts - a countdown until you have to enter your password again, since Steam signs you out completely after a certain period.

**Comment by rex706** [comment]
@marius137 This is actually an interesting idea. 

@Darthagnon the only thing is the account time-out period seems sporadic for me. I can't find any information on exactly how long this time is. Do you mean when you've entered a password incorrectly too many times?
