### ISSUE TITLE
Decrypted Passwords on Encrypted Manager

### ISSUE THREAD

**Issue by ColinTheShark** [rex706/SAM#39]
Somewhat related to #34.

My idea/request was to have the option to display all passwords in clear text when SAM itself is password protected.

Due to accounts from [cathook](https://accgen.cathook.club) being suspended by Steam, we need the Username **and** Password to [get the email back](https://accgen.cathook.club/recovery.html).

**Comment by rex706** [comment]
@ColinTheShark I will think about this. It feels weird exposing that all at once, but since I'm going ahead with #34 anyway I guess it will be fine.
