### ISSUE TITLE
Userdata Folder

### ISSUE THREAD

**Issue by Nou4r** [rex706/SAM#42]
Hey, it would be awesome to have a feature that we can toogle that delets the userdata folder in the steam path.

**Comment by rex706** [comment]
@Nou4r When you say toggle, do you mean it would delete the userdata folder regularly? Or just a button that can clear it manually? Is there a preferred frequency to clear that folder? Like after every login?

**Comment by Nou4r** [comment]
LIke delete it after each successfull logon, as much as possible basically
