### ISSUE TITLE
Remember window position after restart

### ISSUE THREAD

**Issue by pontifezo** [rex706/SAM#43]
Please add an option to remember window position after restart. Each time after program launched, its top left corner is centered at screen and I have to drag it around for better view. 

Also maybe a possibility to set custom size for accounts' buttons wiil be useful.

Thanks.

**Comment by ColinTheShark** [comment]
Well this just became relevant again.

After the [latest release](https://github.com/rex706/SAM/releases/tag/v1.4.0.0) SAM always starts with the top left corner in the middle of the screen.
