### ISSUE TITLE
Keypress is alot more dangerous than parameters

### ISSUE THREAD

**Issue by KyeNormanGill** [rex706/SAM#46]
After updating to 1.3.0 I accidentally alt-tabbed during login, and it keypressed my password into my friends DMs and sent it rofl. I think launch params would be a lot better in my opinion. Maybe make it optional? to choose between launch params and keypresses.

Either that or make sure the steam login UI is in focus, if not wait until it is next, to paste in that.

**Comment by rex706** [comment]
It actually does focus the window for every keypress, especially the password. But I will make using parameters an option and push an update out later today.

**Comment by iebb** [comment]
Another scenario:
When using IMEs (for Chinese/Japanese/Korean inputs), the tab key are often captured by IME (like next page of candidate words), resulting plain-text password displaying in username box. That's pretty dangerous when someone could see your screen.

**Comment by rex706** [comment]
Understood. I will default to logging in with parameters like it used to and push an update when I can after work. I think I can still enable remembering password functionality by setting the reg key value to 1 programmatically. 

Apologies for jumping the gun on this one everyone.
