### ISSUE TITLE
Suggestions #2

### ISSUE THREAD

**Issue by sp0ok3r** [rex706/SAM#5]
* Start with windows but minimized ,
* Maybe add the ability to export all accounts to file,

It really needs to reload steam every time i open sam?
I think before installed sam the login_key worked, this is because that problem of the parameter?

**Comment by rex706** [comment]
Finally have more time to work on this project. Start with windows minimized can be done fairly easily. The accounts are already sort of saved to a file but I suppose I can add a feature to save a copy of that file elsewhere. 

SAM reloading steam every time it opens is a product of using the auto-login feature. I will try to think of a way around this. Maybe only trigger the auto-login if steam is not already open?

**Comment by sp0ok3r** [comment]
Thanks
