### ISSUE TITLE
Window not showing

### ISSUE THREAD

**Issue by KyeNormanGill** [rex706/SAM#52]
Not sure why but after upgrading from 13.01 to 13.03 my window won't come in to focus. I tried deleting the current sam.exe and getting the latest from releases. But it does the same thing.

It sits in my taskbar and bottom panel like any other program but it won't actually pop up when I click on it. The only way I can use it currently is right-clicking the icon on the bottom tray and selecting an account through the small menu.

**Comment by rex706** [comment]
Maybe the saved window location is something weird? You can try deleting the two window location values in the SAMSettings.ini file.

**Comment by KyeNormanGill** [comment]
Ahh yes it was set to 
```
WindowLeft=-32000
WindowTop=-32000
```
Reset it to 0, which fixed it.
