### ISSUE TITLE
Remove Password

### ISSUE THREAD

**Issue by MattiasMoenster2019** [rex706/SAM#55]
The startup password can simply be removed 

You just go to the "SAMSettings" and find "PasswordProtect" make it = false and gg no password

**Comment by rex706** [comment]
But does it still work? If you do that, the file is still encrypted and therefore will fail loading the accounts, right? The application crashes for me in this case. I could have it prompt for a warning or something instead as that probably makes more sense.

**Comment by MattiasMoenster2019** [comment]
Hmm that weird... It did work for me, I just poked around a little trying to find the saved passwords and usernames in file cause when i open the SAM it automatically just minimizes it so i can only change accounts with it by using the icon in the minimized icons tab. Anyway iam getting a little off track xD. So it DID work but its rather glitchy afterwords but is still usable Sorry for my bad english :) -Moenster

**Comment by MattiasMoenster2019** [comment]
here https://youtu.be/9CTCkKQirSQ forgot to sync the audio so it got deleted xD

**Comment by rex706** [comment]
Interesting. I very much appreciate your example video! 

For reference, if you actually had accounts loaded in the application it would not work. 

Also, you can drag the background of the SAM window to move it since I know that when it is small like that it is difficult to grab the top of the window.

**Comment by rex706** [comment]
Currently, I don't see a reasonable way to prevent bypassing the password **if there are no accounts loaded into SAM** without saving extra files or keys to the file system somewhere. Since this is otherwise not a problem if accounts are present, I am closing this issue.
