### ISSUE TITLE
Wrong Password on import

### ISSUE THREAD

**Issue by ColinTheShark** [rex706/SAM#56]
When importing Accounts with the "Delimiter Seperated" function, the accounts get a wrong password.

Using this:
```
username:password
username:password
```
the saved passwords gain an additional and unwanted linebreak at their end, effectively invalidating the password.

**Comment by rex706** [comment]
Interesting. I will take a look into this and try my best to get an update out tomorrow if possible. It should be a simple fix of just removing those characters or blank spaces as I don't think they are allowed in passwords anyway.
