### ISSUE TITLE
The program does not enter SG code.

### ISSUE THREAD

**Issue by lzrdblzzrd** [rex706/SAM#57]
Recently, I used SAM and everything was fine, he entered the code correctly every time. After reinstalling the windows, I ran the same program from the same folder, since I did not format the disk on which it lay, and now it does not enter the Steam Guard code. He just ignores the field. I already exported the accounts and imported into a new downloaded program (maybe there was some kind of error in the program settings), but nothing changed. Maybe there are any programs that are needed for SAM to work?
Again, I repeat that before reinstalling Windows, everything was fine, maybe this is the problem of missing components on my PC.

**Comment by rex706** [comment]
@lzrdblzzrd Someone else was experiencing a similar issue, but you can try running SAM as Administrator, or possibly updating your [.NET Framework](https://dotnet.microsoft.com/download).

Please let me know if this helps!

**Comment by lzrdblzzrd** [comment]
@rex706 Updating the NET Framework and running as administrator did not help, it also ignores the code field.

**Comment by rex706** [comment]
@lzrdblzzrd Maybe it is a language issue, do you run Steam in English? and if not, could you please try? If that is indeed the problem I will try to change the way SAM looks for the Steam Guard window itself to be more universal.

**Comment by lzrdblzzrd** [comment]
@rex706 Well, that worked. I changed the language from Russian to English and he entered the code. Of course, I don’t complain about the language, because I used English Steam before reinstalling Windows and just forgot to change the language, but it seems to me many people would be more comfortable using the language they want.

Thanks!

**Comment by rex706** [comment]
@lzrdblzzrd I completely understand and will take some additional time testing different languages before the next release. Steam could have possibly changed the window name in some cases, but I may be able to detect the 'child' Steam windows without having to know the name. 

Thank you very much for helping me troubleshoot the actual problem so I can get it fixed!

**Comment by rex706** [comment]
@lzrdblzzrd the new version should address this issue and should now work again with languages other than English 😃
