### ISSUE TITLE
Password protection doesn't work

### ISSUE THREAD

**Issue by Validol4ik** [rex706/SAM#58]
I just downloaded your app, set password, added an account, and was asked to enter my password.

So I entered my password, but the app just rejected it (I'm sure it was the same password, I did it all over again 3 times with the same result). 

So at some point, I restarted the app and clicked OK without entering the password, clicked NO when I had been asked if I was sure, clicked OK without entering anything again and finally clicked OK when I had been asked if I was sure. 

Guess what? It logged in and I could log into my steam account though credentials were encrypted (Well, login wasn't encrypted, but the password was). 

P.S. Maybe it's important, I never entered 2FA Shared Secret.

**Comment by rex706** [comment]
So I found the cause for this issue. Turns out SAM was not properly serializing the accounts with your provided password when new accounts were added. I just pushed a commit with the fix and should have a new version out shortly. Thanks for pointing this out and being very descriptive!
