### ISSUE TITLE
later version than 1.3.0.3 Hotfix does not work at all without using -login.

### ISSUE THREAD

**Issue by wazerstar** [rex706/SAM#61]
using no parameters and just using save password will not activate steam window anymore and open random search/program fields instead, wondering

**Comment by wazerstar** [comment]
not working good, fails a lot now.

**Comment by rex706** [comment]
@wazerstar could you please be more specific?

**Comment by wazerstar** [comment]
@rex706 forgot to get back to you, it it still has issues focusing and when it finally gets focus it types password in username and put a asterisk star in password, fails, then it reboots steam to try again and then it just stalls there. I tested with various accounts and did also test after 2 reboots.

**Comment by rex706** [comment]
Sounds like SAM isn't waiting long enough for the Steam Login window to initialize fully in some cases. I'll see what I can do about this.

**Comment by wazerstar** [comment]
@rex706 Version 1.3.0.3 Hotfix worked 100% wonderfull all the time, before you introduced different chars.

**Comment by rex706** [comment]
@wazerstar fair enough, I will take a close look at what exactly changed from that version. I've been busy but should have some time a little later today to take a look and potentially fix.

**Comment by wazerstar** [comment]
@rex706 Works much better again, tho I had it just sitting there "only once" with needing to enter username/password without it closing steam and trying again, tested on 8 accounts.
