### ISSUE TITLE
Not reacting to Steam 2fa window

### ISSUE THREAD

**Issue by oleg1357** [rex706/SAM#67]
The program just stuck at this moment. I got Windows Server 2016, am I missing any dependencies?
![2019-10-17_02-22-13](https://user-images.githubusercontent.com/44361815/66966174-fcd9eb00-f084-11e9-9c62-305e5779d53f.png) BTW works perfectly on win10.

**Comment by rex706** [comment]
@oleg1357 try running as admin or installing the latest [.NET framework](https://dotnet.microsoft.com/download)

**Comment by oleg1357** [comment]
Unfortunately, it doesn't work for me.

**Comment by rex706** [comment]
@oleg1357 is the shared secret for that account entered correctly? 

Now that I think about it I probably need to add a prompt to warn users when there is no shared secret entered for an account that needs one.

I have never tried running the application on windows server 2016 but can try setting up a testing environment later if need be.

**Comment by oleg1357** [comment]
Yes, the secret is correct, I have tried the same .dat file on my home PC, Don`t know if testing is needed on OS like this, not a big deal. What im really thinking of right now is running multiple instances of Steam through SAM, but Sandboxie not working directly with your app.

**Comment by rex706** [comment]
@oleg1357 After a little bit of digging, depending on what version of Sandboxie you have (I've never used this VM before) there is a setting somewhere to allow programs running inside it to simulate keyboard inputs, which may be not allowed by default. See the Hardware Access section at the bottom (although it says it has been removed in newer versions so the setting might be elsewhere if it still exists): https://www.sandboxie.com/RestrictionsSettings
