### ISSUE TITLE
Can't save settings?

### ISSUE THREAD

**Issue by Nou4r** [rex706/SAM#68]
https://streamable.com/u91x0
It does't let me select the "radio box"

**Comment by rex706** [comment]
After checking, the auto log check boxes do not seem to be working like you show, but everything else works for me still. Strange. I will look into the auto log check boxes for now.

**Comment by rex706** [comment]
Please try the latest version. If you still have issues, your SAMSettings.ini file may be corrupt and in that case you may have to delete it and restart SAM so it generates a fresh one.
