### ISSUE TITLE
Suggestions: Ban Check, Drop-Down Timeout

### ISSUE THREAD

**Issue by ColinTheShark** [rex706/SAM#69]
Hey, had a couple ideas to enhance the Account Manager.

1) Add an input field for a [Steam API Key](https://steamcommunity.com/dev/registerkey) which would then check all accounts for a Game Ban and mark the accounts. A single API request can check up to 100 accounts at a time and requires only the ID64 though a full URL works, too.

2) A dropdown menu for the most common cooldowns you can have in CS:GO.

    * 30 minutes
    * 2 hours
    * 24 hours
    * 7 days

    In addition to those a 21 hours option for when you got 2 wins in matchmaking and can't play for a day.

Looking forward to your thoughts on this.

**Comment by rex706** [comment]
Having an input field for the user to input their on API key is a great idea as I'm sure the one that has been hard coded from a long time ago is most likely over used. 

By 'Game Ban', do you mean VAC? Or does the API have awareness of other kinds of bans as well? I'll take a look into the documentation for this to see what options there are. Good to know the request can take up to 100 accounts at a time as well. 

You can already set a 'timeout' on any given account through the context menu, but I guess I could add some quick options like those to make it easier than fiddling with the spin boxes.

**Comment by ColinTheShark** [comment]
> By 'Game Ban', do you mean VAC? Or does the API have awareness of other kinds of bans as well?

When [querying for GetPlayerBans](https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerBans_.28v1.29) the API returns both NumberOfVacBans and NumberOfGameBans. The latter is interesting for CS:GO Overwatch bans 👀 
 
> You can already set a 'timeout' on any given account through the context menu, but I guess I could add some quick options like those to make it easier than fiddling with the spin boxes.

Those spin boxes are a pain in the ass, which makes me use them literally never. It's annoying to have to set the times individually. A drop down for the most common would be awesome to have (I could finally get rid of my Google Spreadsheets lmao)

**Comment by Nou4r** [comment]
This would be super awesome.

**Comment by ColinTheShark** [comment]
> 3 referencing commits

Will there be an ETA for a new update?

**Comment by rex706** [comment]
I'm almost finished with #65. I think the last bit I'm missing is deleting selected accounts while in this view mode, which I'll work on today. I'll likely push out an update after that. 

I forgot to include the issue in the commit so it would display in this thread, but I included the quick timeout options (including 21 hours) as well.
