### ISSUE TITLE
Option to import from text without a shared secret

### ISSUE THREAD

**Issue by lolanonymous** [rex706/SAM#70]
Accounts I've generated from a popular account generator site do not come with a third separator in them, not allowing me to import them.

**Comment by lolanonymous** [comment]
I found how to reproduce, turns out it doesn't like the cursor one line below the accounts as shown. Otherwise it works fine. 
https://i.imgur.com/74VTcSL.png

**Comment by rex706** [comment]
Nice find. Should be an easy fix
