### ISSUE TITLE
SAM not showing bans

### ISSUE THREAD

**Issue by ColinTheShark** [rex706/SAM#73]
Since you've updated SAM to include a ban check for accounts (#69), I have now noticed, that the bans aren't being shown in the app.

I have accounts that I know are banned, but even after updating to the `1.4.0.0` update, those haven't been updated to show the ban status, even though I passed my Steam API Key to the correct field in the settings.

(On a minor side-note: The list view can't be scrolled with the mouse wheel.)

<sup>PS: I hope I'm not annoying with the amount of Issues I've opened recently, there is no other way for me to contact you xD</sup>

**Comment by rex706** [comment]
Have you tried signing into the account at least once before loading the web data? There doesn't seem to be an API call that allows you to query _for_ a user's steamId, and the only way I can reliably get that information currently is from parsing the Steam config.vdf file, which stores user info like the steamId for each account successfully signed into Steam. Is your issue with VAC Bans, Game Bans, or both? Do you know of another reliable way to get a user's steamId without having to enter it manually? I've used the [vanity URL API method](https://wiki.teamfortress.com/wiki/WebAPI/ResolveVanityURL) before, but it is very unreliable unless you have the _actual_ profile URL, which I guess I could try using if the user entered it and the config.vdf file check comes back with nothing useful. 

I will take a look into the scrolling issue as well.

Also, I appreciate you taking the time to bring issues to my attention and wanting to make the app better. Feel free to add me on Discord if you like: rex706#6521

**Comment by ColinTheShark** [comment]
> Have you tried signing into the account at least once before loading the web data?

No, actually not. But I really can't be bothered to log into 100+ accounts just to check if they're banned xD

> There doesn't seem to be an API call that allows you to query for a user's steamId

Oh, if only you knew...

The [API Endpoint](https://github.com/rex706/SAM/issues/69#issuecomment-545512504) I referred to in Issue 69 (hehe) accepts a comma delimited list of Steam `ID64` both in the full URL (`/profiles/123`) and just the ID64 itself. You could use some regex magic to find the ID inside the full URL (`\d{17}`).

Alternatively you can, if the ID doesn't match, use a different Regex, to see if it matches an `/id/` URL with `\w+$` as that would only match against a word at the end of a string (the string being the url).

[Here's an example on what I'm talking about][Regex].

As for an example I have prepared: [This API Request][API] would return 6 accounts as being banned. Replace the XXXXXXX with your own API Key.

I hope that'll make it somewhat clear, I've sent you a request on Discord btw.

[Regex]: https://regex101.com/r/QBXNdu/3
[API]: http://api.steampowered.com/ISteamUser/GetPlayerBans/v1/?key=XXXXXXXXXXXXXXXXXX&steamids=76561198983355245,76561198983360241,https://steamcommunity.com/profiles/76561198983595629,https://steamcommunity.com/profiles/76561198983367530,https://steamcommunity.com/profiles/76561198983570242,https://steamcommunity.com/profiles/76561198983220036,https://steamcommunity.com/profiles/76561198983580297,https://steamcommunity.com/profiles/76561198983323898,https://steamcommunity.com/profiles/76561198983231361,https://steamcommunity.com/profiles/76561198910171832,https://steamcommunity.com/profiles/76561198910086238,https://steamcommunity.com/profiles/76561198910188874,https://steamcommunity.com/profiles/76561198910447857,https://steamcommunity.com/profiles/76561198910189264,https://steamcommunity.com/profiles/76561198910170598

**Comment by ZEROx45** [comment]
ok how to fix it now? cause im still not receiving any data o: 

i have 3 gamebanned accounts?!

**Comment by ColinTheShark** [comment]
> ok how to fix it now?

Until there is a new Release you could try downloading the repository and building the Application yourself. I for my part will wait for a new Release.
