### ISSUE TITLE
Profile Pic Not Being Shown

### ISSUE THREAD

**Issue by silentshotghost** [rex706/SAM#8]
Profile pic not being shown and yes i did add steam url, i even tried editing the .dat file both methods didn't work

**Comment by rex706** [comment]
Steam updated their profile pic urls. Will be fixed in the next update!

**Comment by krsu** [comment]
fixed it temporarily for anyone who doesn't want to wait

https://github.com/rex706/SAM/pull/11

**Comment by rex706** [comment]
Sorry for the delay, been super busy. Will get this fixed asap.

**Comment by rex706** [comment]
Apologies for taking so long to publish this. I ditched the new updater and released like normal.

Please let me know if there are any more problems regarding this.
