### ISSUE TITLE
SAM rapes CPU and bugs out

### ISSUE THREAD

**Issue by Nou4r** [rex706/SAM#87]
Sometimes SAM just won't up and my pc goes crazy, in this case it wasnt as bade but still it used 15% of my cpu and it was frozen.
![image](https://user-images.githubusercontent.com/12816677/72687321-013af780-3afd-11ea-9a41-29a3307abe1f.png)

**Comment by Nou4r** [comment]
This happens if SAM is left for a hour or so alone.

**Comment by rex706** [comment]
I will test this to see if I can reproduce the issue.
