### ISSUE TITLE
Profile Images not loading after reload

### ISSUE THREAD

**Issue by 2Eggsss** [rex706/SAM#89]
Dunno if Valve have updated Profile Image URLS again but images are not loading for a few days for me now, I will check and update as required.

@rex706 please add bug tag, thanks :)

**Comment by Nou4r** [comment]
Works perfectly fine for me, but when i click reload button on a individual account it doesn't work but isn't even important.

**Comment by 2Eggsss** [comment]
> Works perfectly fine for me, but when i click reload button on a individual account it doesn't work but i don't even care because most of the time i just reload all accounts at once.

Reloading all of them at the same time worked fine, but individual reloads fuck up the image so theres still a bug somewhere

**Comment by rex706** [comment]
Looks like Valve added a text element right before where the image is usually found.

**Comment by KittyBabyMan** [comment]
> 
> 
> Looks like Valve added a text element right before where the image is usually found.
> 
> Edit: I've improved the selection to look specifically for the `img` tag.

Hello. This bug is still occurring. Is there a chance this update has been pushed? Or do I need to update? SAM doesn't detect any pending updates, and I don't think the latest download addresses this issue.

**Comment by 2Eggsss** [comment]
> > Looks like Valve added a text element right before where the image is usually found.
> > Edit: I've improved the selection to look specifically for the `img` tag.
> 
> Hello. This bug is still occurring. Is there a chance this update has been pushed? Or do I need to update? SAM doesn't detect any pending updates, and I don't think the latest download addresses this issue.

It's been pushed to the repo, if you need it immediately you need to compile it yourself.

**Comment by KittyBabyMan** [comment]
> 
> 
> > > Looks like Valve added a text element right before where the image is usually found.
> > > Edit: I've improved the selection to look specifically for the `img` tag.
> > 
> > 
> > Hello. This bug is still occurring. Is there a chance this update has been pushed? Or do I need to update? SAM doesn't detect any pending updates, and I don't think the latest download addresses this issue.
> 
> It's been pushed to the repo, if you need it immediately you need to compile it yourself.

Ah, thank you!

**Comment by rex706** [comment]
I am planning to make an official update as soon as it's ready. I know there are a bunch of fixes that are ready to go but there are still a couple of larger outstanding items on my todo list that I have to take care of. I've been a bit more busy with work and other real life things since the new year but I should be able to get back to working on SAM regularly this next week.

**Comment by clahrk** [comment]
When can we expect an update to fix the profile pictures? Thanks.

**Comment by rex706** [comment]
@clahrk I am currently looking more into #78 and #81 and will hopefully have an update out sometime this weekend. I know a update has been long over due so I will do my best to get it out as soon as it is ready.
