### ISSUE TITLE
Right click > Login without Parameter

### ISSUE THREAD

**Issue by Nou4r** [rex706/SAM#90]
^title
would be very nice

**Comment by rex706** [comment]
I apologize, but I might need some additional explanation on what you mean by 'Login without Parameter'. Does this mean you want another context menu item that logs in without any parameters? Does this also include the functionality of the -login parameter? There are a couple of hesitations I have with doing this. Could you please explain a use case that this would be beneficial for?

**Comment by Nou4r** [comment]
In case we per default like to login without the -login parameter, add another context menu item that lets us login to the selected account via the -login parameter.

Hope this is clear enough, thanks again for the great wok on this amazing project.

**Comment by rex706** [comment]
@Nou4r since there are now parameters per account, I think we can close this out.
