### ISSUE TITLE
Padding is invalid and cannot be removed.

### ISSUE THREAD

**Issue by deprale** [rex706/SAM#91]
Title.
It pops up no matter what password I insert.

**Comment by rex706** [comment]
Hm, I'm not quite sure what you mean. Could you please provide a screenshot, if possible?

**Comment by deprale** [comment]
Building my own, it happens when i input any password even if its the correct one...

**Comment by rex706** [comment]
This may be happening if you are using an info.dat file that was created with the release version of SAM then trying to use that file with a version that you built yourself. When you build your own, the key that is used for the initial password encryption is different and doing a quick google search of "Padding is invalid and cannot be removed" reveals a lot of issues regarding this same problem. If you don't want to wait for an official release, you will likely have to reconfigure the accounts you want to use from scratch to generate a new info.dat file.
