### ISSUE TITLE
Wrong Shared Secret handling

### ISSUE THREAD

**Issue by ColinTheShark** [rex706/SAM#92]
After I updated today, SAM didn't authenticate the 2FA correctly. It only entered some jumbled mess with percent and dollar signs, closing brackets and the like. Re-entering the Shared Secret didn't help and I had to fall back to Steam Desktop Authenticator to get a correct 2FA code.

Sadly I don't have any screenshots to help here.

**Comment by rex706** [comment]
I had adopted some functionality another user came up with to handle the Microsoft IME when entering the Steam Guard code. This simply activates the caps lock before the code is typed and deactivates it if it was not activated prior. I'm not sure how this would affect anything, as after many tests I do not experience any issue, but maybe I will have to create a toggle setting for it if it is the root of this issue. Thoughts?

**Comment by ColinTheShark** [comment]
Activating capslock sounds like a bad idea, as the input is auto-capsed by the steam client.
Activating Capslock makes 8s and 9s become ( and ).

[Also I made a gif.](https://files.catbox.moe/nu88bv.mp4)

![](https://files.catbox.moe/fna3us.gif)

**Comment by rex706** [comment]
Alright, then I think the best solution would then be to make a toggle setting so users who need it can enable it.  I will have a fix out soon.
