### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by NNiX1** [rex706/SAM#97]
I need to change setting but whenever i click on setting it freezes and crashes 100% of time

**Comment by rex706** [comment]
Have you tried running as Admin? The application may have an issue saving the settings file if installed somewhere like in the Program Files directories.

**Comment by rex706** [comment]
You may need [.NET Framework 4.8](https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer) if you don't already have it.
