### ISSUE TITLE
2FA problem

### ISSUE THREAD

**Issue by MattiasMoenster2019** [rex706/SAM#98]
My account with 2FA enabled won't "auto login" i have the shared secret from Mafiles in sda and i ran SAM in administrator mode i don't see what iam doing wrong?

**Comment by rex706** [comment]
The auto login feature is only triggered if Steam is not already running. Could this be the problem?

**Comment by MattiasMoenster2019** [comment]
No it does not seem to be the problem have tried with steam closed and open (Checked in joblist)
I reinstalled the program (And steam) Multiple times even tried it on a newly installed pc and the 2fa simply does not work for me anymore :( It was a great service while it worked tho! Rly hope you get it fixed would be epic :)

**Comment by rex706** [comment]
I think I misunderstood the problem originally. It is specifically just with the 2FA? Does it hang on the Steam Guard window? Is anything entered into the Steam Guard box? Is Steam opened at all by SAM?

**Comment by MattiasMoenster2019** [comment]
Yes it just opens the login thingy uses the username:password then when the steam guard opens it does nothing at all (No wrong text entered)

**Comment by rex706** [comment]
After a lot of thinking, the issue might be that SendMessage and PostMessage are blocked in some cases. SendKeys is what was being used before, which may have worked for you previously. I will think about how to implement an option to select the automatic input method and options like Microsoft IME.

**Comment by MattiasMoenster2019** [comment]
Okok and Ty for your time. Have a great day :)

**Comment by rex706** [comment]
Please try the SendWait option 
![image](https://user-images.githubusercontent.com/15636269/80915982-c1062a80-8d23-11ea-806f-2cf48ab9084b.png)
