### ISSUE TITLE
2fa doesnt support win 7 mode

### ISSUE THREAD

**Issue by tempestuz** [rex706/SAM#99]
doesnt fill in 2fa in win7 sandbox

**Comment by rex706** [comment]
This may be related to #98. I made options to select which auto input method to use, since it was changed recently to support something else, but can probably be changed back without any issues for most users. I will prep an update and get that out today.

**Comment by rex706** [comment]
Please try the SendWait option 
![image](https://user-images.githubusercontent.com/15636269/80915982-c1062a80-8d23-11ea-806f-2cf48ab9084b.png)
